name: "Vault"
main: com.example.vault.VaultPlugin
version: v1.3
api-version: 1.13
description: Internal Economy provider like Vault 2.0 (no Vault.jar dependency)
softdepend: [LuckPerms, PlaceholderAPI]
commands:
  vault:
    description: Admin command for Vault
    usage: /vault reload|update
    permission: vault.admin
permissions:
  vault.admin:
    description: Allows using /vault reload and update
    default: op